name: Cortex Profile

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: AbdullahBakir97/cortex@v1
        with:
          config: .github/cortex.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
